spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost/inventory?connectionCollation=utf8mb4_bin&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ''
    maximum-pool-size: 1
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    kr.lul.kobalttown: trace
