spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/inventory?allowPublicKeyRetrieval=true
      username: test
      password: 'HU]iaet]zE}p6QJY88QHd9*Cb3VJR^Mcoxqax9dr7QLMGA3/{Drn,AJ]c9=zWMD6'
      maximum-pool-size: 1
  jpa:
    show-sql: false
    open-in-view=: false
    properties:
      hibernate:
        show_sql: false
        hbm2ddl:
          auto: update
  thymeleaf:
    cache: false
    prefix: file:./front/templates/
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%logger#%M L.%line){cyan} %clr(:){faint} %m%n%wEx'
  level:
    root: warn
    org.hibernate.SQL: debug
    kr.lul.inventory: trace
    kr.lul.inventory.runner: warn
    kr.lul.inventory.web.manager.support.LoggingHandlerInterceptor: info
