-- MySQL Script generated by MySQL Workbench
-- Sun Jul 21 14:07:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inventory` ;

-- -----------------------------------------------------
-- Schema inventory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventory` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ;
SHOW WARNINGS;
USE `inventory` ;

-- -----------------------------------------------------
-- Table `mgr_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgr_manager` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_520_ci' NOT NULL,
  `name` VARCHAR(64) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_520_ci' NOT NULL,
  `created_utc` BIGINT NOT NULL,
  `updated_utc` BIGINT NOT NULL,
  `modify_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_MANAGER_EMAIL` (`email` ASC),
  UNIQUE INDEX `UQ_MANAGER_NAME` (`name` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cfg_noun_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cfg_noun_type` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `modify_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_NOUN_TYPE_NAME` (`name` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mgr_noun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgr_noun` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `manager` INT UNSIGNED NOT NULL,
  `noun_type` INT UNSIGNED NOT NULL,
  `noun_key` VARCHAR(255) NOT NULL,
  `label` VARCHAR(255) NOT NULL,
  `label_code` VARCHAR(255) NOT NULL,
  `max_cnt` INT UNSIGNED NULL DEFAULT NULL,
  `created_utc` BIGINT NOT NULL,
  `updated_utc` BIGINT NOT NULL,
  `modify_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `FK_NOUN_PK_MANAGER` (`manager` ASC),
  INDEX `FK_NOUN_PK_NOUN_TYPE` (`noun_type` ASC),
  UNIQUE INDEX `UQ_NOUN_KEY` (`noun_key` ASC),
  CONSTRAINT `FK_NOUN_PK_MANAGER`
    FOREIGN KEY (`manager`)
    REFERENCES `mgr_manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_NOUN_PK_NOUN_TYPE`
    FOREIGN KEY (`noun_type`)
    REFERENCES `cfg_noun_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mgr_manager_credential`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mgr_manager_credential` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `manager` INT UNSIGNED NOT NULL,
  `public_key` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `secret_hash` VARCHAR(60) NOT NULL,
  `created_utc` BIGINT NOT NULL,
  `modify_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `FK_MANAGER_CREDENTIAL_PK_MANAGER` (`manager` ASC),
  UNIQUE INDEX `UQ_MANAGER_CREDENTIAL_PUBLIC_KEY` (`public_key` ASC),
  CONSTRAINT `FK_MANAGER_CREDENTIAL_PK_MANAGER`
    FOREIGN KEY (`manager`)
    REFERENCES `mgr_manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
USE `inventory` ;

-- -----------------------------------------------------
-- View `view_manager`
-- -----------------------------------------------------
USE `inventory`;
CREATE  OR REPLACE VIEW `view_manager` AS
    SELECT 
        `m`.`id`,
        `m`.`email`,
        `m`.`name`,
        `m`.`created_utc`,
        `m`.`updated_utc`,
        `c`.`id` AS `cid`,
        `c`.`public_key`,
        `c`.`secret_hash`,
        `c`.`created_utc` AS `credential_created_utc`
    FROM
        `mgr_manager` AS `m`,
        `mgr_manager_credential` AS `c`
    WHERE
        `m`.`id` = `c`.`manager`
    ORDER BY `m`.`id` ASC , `c`.`id` ASC
;
SHOW WARNINGS;

-- -----------------------------------------------------
-- View `view_noun`
-- -----------------------------------------------------
USE `inventory`;
CREATE  OR REPLACE VIEW `view_noun` AS
    SELECT 
        `n`.`id`,
        `n`.`manager` AS `manager_id`,
        `m`.`name` AS `manager`,
        `t`.`name` AS `noun_type`,
        `n`.`noun_key`,
        `n`.`label`,
        `n`.`label_code`,
        `n`.`max_cnt`,
        `n`.`created_utc`,
        `n`.`updated_utc`,
        `n`.`modify_ts`
    FROM
        `mgr_noun` AS `n`,
        `mgr_manager` AS `m`,
        `cfg_noun_type` AS `t`
    WHERE
        `n`.`manager` = `m`.`id`
            AND `n`.`noun_type` = `t`.`id`
    ORDER BY `n`.`id` ASC
;
SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cfg_noun_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `inventory`;
INSERT INTO `cfg_noun_type` (`id`, `name`, `modify_ts`) VALUES (0, 'IDENTIFIABLE', DEFAULT);
INSERT INTO `cfg_noun_type` (`id`, `name`, `modify_ts`) VALUES (1, 'COUNTABLE', DEFAULT);
INSERT INTO `cfg_noun_type` (`id`, `name`, `modify_ts`) VALUES (2, 'LIMITED_IDENTIFIABLE', DEFAULT);
INSERT INTO `cfg_noun_type` (`id`, `name`, `modify_ts`) VALUES (3, 'LIMITED_COUNTABLE', DEFAULT);

COMMIT;

